name: Movie Alert

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          DISTRICT_GUEST_TOKEN: ${{ secrets.DISTRICT_GUEST_TOKEN }}
        run: python movie_alert.py

      - name: Commit State
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add state.json

          git diff --cached --quiet || git commit -m "update state"

          git push
